### ISSUE TITLE
Help with raw text from feeds

### ISSUE THREAD

**Issue by Nubuki-all** [c3kay/hoyolab-rss-feeds#15]
Can a raw_text or summary field be added for each feed?
Could be a list (per images)

**Comment by c3kay** [comment]
A summary would be possible. Both Atom and JSON-Feed define a `summary` as a possible field for an entry. A short summary/description is also served as plain text without format by the Hoyolab API. Is this what you would like to have? If not, please elaborate on your idea!

Please note, that this project aims on providing valid (RSS) feeds in Atom and JSON-Feed format. Custom fields that do not correspond to the standards will not be accepted.

**Comment by Nubuki-all** [comment]
Yup this works, thank you

**Comment by c3kay** [comment]
Alright, I will try to implement it, when I find the time for it!

**Comment by c3kay** [comment]
Implemented in v2.4.1 (#17). The hosted feeds are also updated now.

**Comment by Nubuki-all** [comment]
Thank you 😊
