### ISSUE TITLE
is there support for other languages? like Chinese?

### ISSUE THREAD

**Issue by seriaati** [c3kay/hoyolab-rss-feeds#2]

**Comment by c3kay** [comment]
Hey there!

Yes, all languages that Hoyolab offers are supported (Go to hoyolab.com for a complete list), but the feeds on my server are only in English.

If you want to host the feeds by yourself, you can set the language in the config file (see `example.conf`). Use the common IETF BCP 47 language tags. For Chinese you can use `zh-tw`. 

If you want to use my script as module, you can set set the `lang` parameter for the `create_game_feeds` function.
